In [186]:
import numpy as np

In [187]:
x = [[32,2,45],[21,3,5]]
y = np.array(x, ndmin = 10)
print(y)
y.ndim

[[[[[[[[[[32  2 45]
         [21  3  5]]]]]]]]]]


10

In [188]:
y = np.array([[[[[[[[[23,34,2]]],[[[34,12,76]]],[[[8,45,65]]],[[[90,43,87]]]]]]]]])
y.ndim
y[0,0,0,0,0,2,0,0,1]

np.int64(45)

In [189]:
x = ("Hello World")
print(x[0:2],x[6:11])
df = len(x)
print(df)

He World
11


In [190]:
arr = np.array(['Swathi','Archana','Vichithra'],dtype="S")
arr.dtype

dtype('S9')

In [191]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('i')
newarr



float64


array([1, 2, 3], dtype=int32)

In [192]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('b')
newarr

float64


array([1, 2, 3], dtype=int8)

In [193]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('c')
newarr


float64


array([b'1', b'2', b'3'], dtype='|S1')

In [194]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('m')
newarr

float64


array([1, 2, 3], dtype=timedelta64)

In [195]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('O')
newarr

float64


array([1.1, 2.1, 3.1], dtype=object)

In [196]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('S')
newarr

float64


array([b'1.1', b'2.1', b'3.1'], dtype='|S32')

In [197]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('U')
newarr

float64


array(['1.1', '2.1', '3.1'], dtype='<U32')

In [198]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('V')
newarr

float64


array([b'\x9A\x99\x99\x99\x99\x99\xF1\x3F',
       b'\xCD\xCC\xCC\xCC\xCC\xCC\x00\x40',
       b'\xCD\xCC\xCC\xCC\xCC\xCC\x08\x40'], dtype='|V8')

In [199]:
arr = np.array(['2023-01-20','2029-09-10','1998-10-23'])
print(arr.dtype)
newarr = arr.astype('M')
newarr

<U10


array(['2023-01-20', '2029-09-10', '1998-10-23'], dtype='datetime64[D]')

In [200]:
arr = np.array([-1,2,-3])
print(arr.dtype)
newarr = arr.astype('u1')
newarr

int64


array([255,   2, 253], dtype=uint8)

In [201]:
arr = np.array([1,2,3,4,5])
x= arr.copy()
print(x)
arr[0] = 42
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [202]:
arr = np.array([1,2,3,4,5])
x= arr.view()
print(x)
arr[0] = 42
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [203]:
df = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(df)
for i in df:
    #print(i)
    for j in i:
        #print(j)
        for k in j:
            print(k)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
1
2
3
4
4
5
6
7
7
8
9
10


In [204]:
x=np.array([[[[[[1,2,3,4,5]]]]]])
for i in np.nditer(x):
    print(i)

1
2
3
4
5


In [205]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
newarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [206]:
arr = np.array([[[[[1,2,3,4,5,6,7,8,9,10,11,12]]]]])
newarr = arr.reshape(-1)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [207]:
a = np.array([[1,2,3]])
y = np.nditer(a,flags = ['buffered'],op_dtypes=['float'])
for x in y:
    print(x)

1.0
2.0
3.0


In [208]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [209]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [210]:
# arr1 = np.array([[1,2,3],[4,5,6]])
# arr1 = np.array([[5,11,14],[7,8,9]])
# arr = np.hstack((arr1,arr2))
# print(arr)

In [211]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[5,11,14],[7,8,9]])
arr = np.vstack((arr1,arr2))
print(arr)

[[ 5 11 14]
 [ 7  8  9]
 [ 4  5  6]]


In [212]:
# arr1 = np.array([[1,2,3],[4,5,6]])
# arr1 = np.array([[5,11,14],[7,8,9]])
# arr = np.dstack((arr1,arr2))
# print(arr)

In [213]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,6)
print(newarr)
arr = np.array([7,8,9,10])
newarr = np.array_split(arr,7)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([7]), array([8]), array([9]), array([10]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [214]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr,6,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64)]


In [215]:
arr = np.array([1,2,33,4,6,7,8,5,6,6,7,9,0])
x = np.where(arr==7)
print(x)

(array([ 5, 10]),)


In [216]:
arr = np.array([3,4,5,6,1,2,4,3])
np.sort(arr)

array([1, 2, 3, 3, 4, 4, 5, 6])

In [217]:
arr = np.array([3,4,5,6,1,2,4,3])
np.argsort(arr)

array([4, 5, 0, 7, 1, 6, 2, 3])

In [218]:
arr = np.array([3,2,0,1,7,8,6])
np.sort(arr)[::-1]

array([8, 7, 6, 3, 2, 1, 0])

In [219]:
arr = np.array([41,42,43,44])
x = np.array([True,False,True,False])
arr[x]

array([41, 43])

In [220]:
arr = np.array([41,42,43,44,45,46,47,48,49,50,51])
filter_arr = []
for i in arr:
    if i<45:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
arr[filter_arr]



array([41, 42, 43, 44])

In [221]:
from numpy import random 
x = random.randint(10)
x

4

In [222]:
x = random.rand()
x

0.17888092917701215

In [223]:
x = random.randint(1000,9999,size = 10)
x

array([4507, 2117, 1430, 4425, 4951, 9822, 7856, 6506, 9265, 5173],
      dtype=int32)

In [224]:
x = random.rand(3,5)
x

array([[0.29500508, 0.74413372, 0.93534456, 0.43818019, 0.82872452],
       [0.02037601, 0.7283329 , 0.59667443, 0.31262296, 0.52491187],
       [0.27765371, 0.41898201, 0.72601417, 0.67201536, 0.39982201]])

In [231]:
choose = ['hi','hello','bye','goodbye']
x = random.choice(choose)
x

np.str_('hello')

In [232]:
x = random.choice([3,5,7,9],size = (3,5))
x

array([[3, 9, 3, 3, 5],
       [7, 9, 9, 9, 9],
       [7, 3, 9, 5, 5]])

In [233]:
x = random.choice([3,5,7,9],size = (10))
x

array([9, 3, 3, 7, 7, 7, 9, 3, 3, 3])

In [236]:
arr = np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[1 3 5 4 2]
