In [2]:
# pip install numpy

In [3]:
import numpy as np

In [4]:
x = [[32,2,45],[21,3,5]]
y = np.array(x, ndmin = 10)
print(y)
y.ndim

[[[[[[[[[[32  2 45]
         [21  3  5]]]]]]]]]]


10

In [5]:
y = np.array([[[[[[[[[23,34,2]]],[[[34,12,76]]],[[[8,45,65]]],[[[90,43,87]]]]]]]]])
y.ndim
y[0,0,0,0,0,2,0,0,1]

np.int64(45)

In [6]:
x = ("Hello World")
print(x[0:2],x[6:11])
df = len(x)
print(df)

He World
11


In [7]:
arr = np.array(['Swathi','Archana','Vichithra'],dtype="S")
arr.dtype

dtype('S9')

In [8]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('i')
newarr



float64


array([1, 2, 3], dtype=int32)

In [9]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('b')
newarr

float64


array([1, 2, 3], dtype=int8)

In [10]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('c')
newarr


float64


array([b'1', b'2', b'3'], dtype='|S1')

In [11]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('m')
newarr

float64


array([1, 2, 3], dtype=timedelta64)

In [12]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('O')
newarr

float64


array([1.1, 2.1, 3.1], dtype=object)

In [13]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('S')
newarr

float64


array([b'1.1', b'2.1', b'3.1'], dtype='|S32')

In [14]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('U')
newarr

float64


array(['1.1', '2.1', '3.1'], dtype='<U32')

In [15]:
arr = np.array([1.1,2.1,3.1])
print(arr.dtype)
newarr = arr.astype('V')
newarr

float64


array([b'\x9A\x99\x99\x99\x99\x99\xF1\x3F',
       b'\xCD\xCC\xCC\xCC\xCC\xCC\x00\x40',
       b'\xCD\xCC\xCC\xCC\xCC\xCC\x08\x40'], dtype='|V8')

In [16]:
arr = np.array(['2023-01-20','2029-09-10','1998-10-23'])
print(arr.dtype)
newarr = arr.astype('M')
newarr

<U10


array(['2023-01-20', '2029-09-10', '1998-10-23'], dtype='datetime64[D]')

In [17]:
arr = np.array([-1,2,-3])
print(arr.dtype)
newarr = arr.astype('u1')
newarr 

int64


array([255,   2, 253], dtype=uint8)

In [18]:
arr = np.array([1,2,3,4,5])
x= arr.copy()
print(x)
arr[0] = 42
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [19]:
arr = np.array([1,2,3,4,5])
x= arr.view()
print(x)
arr[0] = 42
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [20]:
df = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(df)
for i in df:
    #print(i)
    for j in i:
        #print(j)
        for k in j:
            print(k)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
1
2
3
4
4
5
6
7
7
8
9
10


In [21]:
x=np.array([[[[[[1,2,3,4,5]]]]]])
for i in np.nditer(x):
    print(i)

1
2
3
4
5


In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
newarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr = np.array([[[[[1,2,3,4,5,6,7,8,9,10,11,12]]]]])
newarr = arr.reshape(-1)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
a = np.array([[1,2,3]])
y = np.nditer(a,flags = ['buffered'],op_dtypes=['float'])
for x in y:
    print(x)

1.0
2.0
3.0


In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,11,14],[7,8,9]])
arr = np.hstack((arr1,arr2))
print(arr)

[[ 1  2  3  5 11 14]
 [ 4  5  6  7  8  9]]


In [28]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[5,11,14],[7,8,9]])
arr = np.vstack((arr1,arr2))
print(arr)

[[ 5 11 14]
 [ 7  8  9]
 [ 5 11 14]
 [ 7  8  9]]


In [29]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,11,14],[7,8,9]])
arr = np.dstack((arr1,arr2))
print(arr)

[[[ 1  5]
  [ 2 11]
  [ 3 14]]

 [[ 4  7]
  [ 5  8]
  [ 6  9]]]


In [30]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,6)
print(newarr)
arr = np.array([7,8,9,10])
newarr = np.array_split(arr,7)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([7]), array([8]), array([9]), array([10]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr,6,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64)]


In [32]:
arr = np.array([1,2,33,4,6,7,8,5,6,6,7,9,0])
x = np.where(arr==7)
print(x)

(array([ 5, 10]),)


In [33]:
arr = np.array([3,4,5,6,1,2,4,3])
np.sort(arr)

array([1, 2, 3, 3, 4, 4, 5, 6])

In [34]:
arr = np.array([3,4,5,6,1,2,4,3])
np.argsort(arr)

array([4, 5, 0, 7, 1, 6, 2, 3])

In [35]:
arr = np.array([3,2,0,1,7,8,6])
np.sort(arr)[::-1]

array([8, 7, 6, 3, 2, 1, 0])

In [36]:
arr = np.array([41,42,43,44])
x = np.array([True,False,True,False])
arr[x]

array([41, 43])

In [37]:
arr = np.array([41,42,43,44,45,46,47,48,49,50,51])
filter_arr = []
for i in arr:
    if i<45:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
arr[filter_arr]



array([41, 42, 43, 44])

In [38]:
from numpy import random 
x = random.randint(10)
x

7

In [39]:
x = random.rand()
x

0.9255067323504409

In [40]:
x = random.randint(1000,9999,size = 10)
x

array([5436, 9131, 6264, 3793, 4567, 7933, 7390, 8265, 1614, 5132],
      dtype=int32)

In [41]:
x = random.rand(3,5)
x

array([[0.57701393, 0.08784386, 0.40493072, 0.7811797 , 0.65155066],
       [0.2519612 , 0.75817238, 0.35858713, 0.9322359 , 0.40986911],
       [0.15547783, 0.87618201, 0.56121776, 0.81853357, 0.90533784]])

In [42]:
choose = ['hi','hello','bye','goodbye']
x = random.choice(choose)
x

np.str_('hi')

In [43]:
x = random.choice([3,5,7,9],size = (3,5))
x

array([[3, 5, 9, 7, 9],
       [3, 5, 3, 9, 9],
       [9, 9, 3, 9, 9]])

In [44]:
x = random.choice([3,5,7,9],size = (10))
x

array([9, 5, 7, 5, 5, 3, 9, 3, 5, 3])

In [45]:
arr = np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[4 2 3 1 5]


Random Data Distribution

In [50]:
x = random.choice([3,5,7,9], p=[0.25,0.25,0.25,0.25],size=(10))
x

array([5, 7, 3, 7, 9, 7, 5, 9, 7, 9])

In [51]:
arr = np.array([1,2,3,4,5])
random.shuffle(arr)
arr

array([1, 5, 3, 2, 4])

In [54]:
arr = np.array([1,2,3,4,5])
print(random.permutation(arr))


[2 1 5 3 4]
